# 🎯 Welcome to Your Programming Evolution

**Today marks a pivotal moment**: You're transitioning from code writer to code director, and you're starting your final assignment! By the end of today's workshop, you'll have made genuine progress on your Smart Finance Assistant project.

**Workshop Goals:**
- Practice AI-assisted data processing with business data
- Start your actual Smart Finance Assistant assignment
- Make your first meaningful GitHub commit
- Build confidence with the new AI collaboration workflow

---

# Part 1: Mindset Shift Demo (20 minutes)

## 🔄 The Workflow Revolution

Let's demonstrate the difference between old-school programming and AI collaboration.

### Old Way Demo: Manual Coding

Imagine trying to analyze spending data the traditional way:

```python
# Old approach - lots of manual work and potential errors
import pandas as pd

# Load data with potential issues
df = pd.read_csv('transactions.csv')

# Oh no! Amounts have dollar signs - need to clean manually
df['Amount'] = df['Amount'].str.replace('$', '')
df['Amount'] = pd.to_numeric(df['Amount'])

# Calculate totals by category - hoping syntax is right
category_totals = {}
for index, row in df.iterrows():
    if row['Category'] in category_totals:
        category_totals[row['Category']] += row['Amount']
    else:
        category_totals[row['Category']] = row['Amount']

# Sort manually
sorted_categories = sorted(category_totals.items(), key=lambda x: x[1], reverse=True)
print(sorted_categories)
```

**Problems with this approach:**
- Lots of syntax to remember
- Easy to make mistakes
- Repetitive patterns
- Hard to modify or extend
- Time-consuming debugging

### New Way Demo: AI Collaboration

Now let's see the AI-assisted approach:

::: {.callout-note}
## AI Collaboration Example

**Your Prompt to AI:**
*"I have a CSV file with columns Date, Amount, Category, Description. The Amount column has dollar signs that need cleaning. I want to calculate total spending by category and show results sorted from highest to lowest. Please write pandas code with comments explaining each step."*

**AI Response:**
:::

```python
import pandas as pd

# Load the transaction data
df = pd.read_csv('transactions.csv')

# Clean the Amount column by removing dollar signs and converting to numeric
df['Amount'] = pd.to_numeric(df['Amount'].str.replace('$', ''), errors='coerce')

# Remove any rows where Amount couldn't be converted (invalid data)
df = df.dropna(subset=['Amount'])

# Calculate total spending by category
category_spending = df.groupby('Category')['Amount'].sum()

# Sort from highest to lowest spending
category_spending = category_spending.sort_values(ascending=False)

# Display results in a business-friendly format
print("💰 Spending Summary by Category")
print("=" * 35)
for category, amount in category_spending.items():
    print(f"{category:<15}: ${amount:>8.2f}")

print(f"\n📊 Total Spending: ${category_spending.sum():.2f}")
```

**Benefits of AI collaboration:**
- ✅ Clear, commented code
- ✅ Handles data cleaning automatically
- ✅ Business-friendly output formatting
- ✅ Easy to understand and modify
- ✅ Professional code structure

## 🤔 Your Assignment Isn't Scary!

**Here's the secret**: Your Smart Finance Assistant assignment is just an extension of what we're doing today. It uses:

- **CSV data processing** (what we're learning now)
- **AI assistance** (what we're practicing now)
- **Gradio interface** (simple web UI - we'll cover this later)
- **Business insights** (your analysis skills)

**By starting today, you're already 10% done with your final project!**

---

# Part 2: Guided Practice with Sample Data (30 minutes)

Let's practice AI collaboration with real business data before moving to your assignment.

## 📁 Loading Sample Data

First, let's load our sample transaction data:

In [9]:
import pandas as pd
import os

# Define the directory and file path
data_dir = '../data'
file_path = os.path.join(data_dir, 'transactions.csv')

# Create the data directory if it doesn't exist
if not os.path.exists(data_dir):
    os.makedirs(data_dir)

# Create a dummy CSV file for demonstration if it doesn't exist
if not os.path.exists(file_path):
    dummy_data = {
        'Date': ['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04', '2023-01-05'],
        'Amount': ['$50.00', '$25.50', '$120.00', '$30.75', '$75.00'],
        'Category': ['Food', 'Transport', 'Shopping', 'Food', 'Utilities'],
        'Description': ['Groceries', 'Bus fare', 'New clothes', 'Restaurant', 'Electricity bill']
    }
    dummy_df = pd.DataFrame(dummy_data)
    dummy_df.to_csv(file_path, index=False)
    print(f"Created a dummy transactions.csv at {file_path}")

# Load the sample transactions
df = pd.read_csv(file_path)

# Display the first few rows to understand our data
print("📋 Sample Transaction Data:")
print("=" * 40)
print(df.head())

print(f"\n📊 Dataset Info:")
print(f"Total transactions: {len(df)}")

# Convert 'Date' column to datetime objects for proper min/max calculation
df['Date'] = pd.to_datetime(df['Date'])
print(f"Date range: {df['Date'].min().strftime('%Y-%m-%d')} to {df['Date'].max().strftime('%Y-%m-%d')}")
print(f"Categories: {df['Category'].unique()}")

Created a dummy transactions.csv at ../data/transactions.csv
📋 Sample Transaction Data:
========================================
         Date   Amount   Category       Description
0  2023-01-01   $50.00       Food         Groceries
1  2023-01-02   $25.50  Transport          Bus fare
2  2023-01-03  $120.00   Shopping       New clothes
3  2023-01-04   $30.75       Food        Restaurant
4  2023-01-05   $75.00  Utilities  Electricity bill

📊 Dataset Info:
Total transactions: 5
Date range: 2023-01-01 to 2023-01-05
Categories: ['Food' 'Transport' 'Shopping' 'Utilities']

## 🤖 AI Collaboration Exercise 1: Basic Analysis

**Your Turn**: Practice prompting AI for basic data analysis.

::: {.callout-tip}
## Practice Prompt Template

Try asking AI:
*"Using this transaction DataFrame, I want to understand my spending patterns. Please create code that shows:
1. Total spending by category
2. Average transaction amount by category  
3. Number of transactions per category
Format the output to be easy to read for a business presentation."*
:::

**Expected AI Response** (try this yourself first!):

In [14]:
# AI-generated solution for spending analysis

# First, clean the 'Amount' column: remove dollar signs and convert to numeric
# Use errors='coerce' to turn any values that cannot be converted into NaN
df['Amount_Cleaned'] = pd.to_numeric(df['Amount'].str.replace('$', '', regex=False), errors='coerce')

# Drop rows where 'Amount_Cleaned' is NaN (invalid transactions)
df.dropna(subset=['Amount_Cleaned'], inplace=True)

# Calculate comprehensive spending summary using the cleaned column
spending_analysis = df.groupby('Category')['Amount_Cleaned'].agg(
    Total_Spent='sum',
    Avg_Amount='mean',
    Transaction_Count='count'
).round(2)

# Sort by total spending
spending_analysis = spending_analysis.sort_values('Total_Spent', ascending=False)

print("💼 Business Spending Analysis")
print("=" * 50)
print(f"{'Category':<15} {'Total':<10} {'Average':<10} {'Count':<8}")
print("-" * 50)

for category, row in spending_analysis.iterrows():
    total = row['Total_Spent']
    avg = row['Avg_Amount']
    count = row['Transaction_Count']
    print(f"{category:<15} ${total:<9.2f} ${avg:<9.2f} {count:<8.0f}")

print(f"\nGrand Total: ${spending_analysis['Total_Spent'].sum():.2f}")

💼 Business Spending Analysis
==================================================
Category        Total      Average    Count
--------------------------------------------------
Shopping        $120.00    $120.00    1
Food            $80.75     $40.38     2
Utilities       $75.00     $75.00     1
Transport       $25.50     $25.50     1

Grand Total: $301.25

## 🔍 Practice Your Critique Skills

Look at the AI-generated code above. Apply your critique toolkit:

1. **Do you understand each line?**
2. **Is it handling the dollar signs correctly?**
3. **Is the output business-appropriate?**
4. **What would you ask AI to improve?**

::: {.callout-warning}
## Critique Practice

The code above has an issue with handling the dollar signs in a grouped operation. How would you prompt AI to fix this?

**Sample critique prompt:**
*"The code is trying to clean dollar signs inside the groupby operation, which is inefficient. Can you first clean the Amount column once, then do the groupby analysis? Also add error handling for invalid amounts."*
:::

## 🤖 AI Collaboration Exercise 2: Business Insights

**Challenge**: Ask AI to help you identify spending patterns that would be useful for financial planning.

**Sample prompt to try:**
*"Based on this spending data, help me identify potential areas where I could reduce expenses. Look for categories with high spending or frequent transactions that might represent opportunities for savings."*

In [16]:
# AI-generated business insights for expense reduction

print("📈 Financial Planning Insights: Opportunities for Savings")
print("=" * 60)

if not spending_analysis.empty:
    # Identify categories with highest spending
    top_spending_category = spending_analysis.iloc[0]
    print(f"\n💸 **Highest Spending Category:** {top_spending_category.name} with a total of ${top_spending_category['Total_Spent']:.2f}.")
    print("   * **Recommendation:** Review transactions in this category. Are there recurring subscriptions, impulse purchases, or alternatives that could reduce this amount?")

    # Identify categories with frequent transactions but possibly lower individual amounts
    # This might indicate small, regular expenses that add up
    frequent_categories = spending_analysis[spending_analysis['Transaction_Count'] > 1].sort_values('Transaction_Count', ascending=False)
    if not frequent_categories.empty:
        print("\n🔍 **Categories with Frequent Transactions (Potential for Small Savings):**")
        for category, row in frequent_categories.iterrows():
            print(f"   - {category}: {int(row['Transaction_Count'])} transactions totaling ${row['Total_Spent']:.2f} (Average: ${row['Avg_Amount']:.2f})")
        print("   * **Recommendation:** Small, frequent expenses can accumulate. Consider budgeting for these, or finding ways to reduce the frequency or average cost of each transaction (e.g., packing lunch instead of buying daily).")
    else:
        print("\n🔍 No categories with multiple transactions identified in this dataset.")

    # Overall spending summary
    grand_total = spending_analysis['Total_Spent'].sum()
    print(f"\n📊 **Overall Financial Snapshot:**")
    print(f"   * Your total spending across all categories for this period is: ${grand_total:.2f}")
    print("   * To improve financial health, consider setting spending targets for each category and tracking against them.")

    print("\n--- End of Insights ---")
else:
    print("No spending data available for analysis.")

📈 Financial Planning Insights: Opportunities for Savings
============================================================

💸 **Highest Spending Category:** Shopping with a total of $120.00.
   * **Recommendation:** Review transactions in this category. Are there recurring subscriptions, impulse purchases, or alternatives that could reduce this amount?

🔍 **Categories with Frequent Transactions (Potential for Small Savings):**
   - Food: 2 transactions totaling $80.75 (Average: $40.38)
   * **Recommendation:** Small, frequent expenses can accumulate. Consider budgeting for these, or finding ways to reduce the frequency or average cost of each transaction (e.g., packing lunch instead of buying daily).

📊 **Overall Financial Snapshot:**
   * Your total spending across all categories for this period is: $301.25
   * To improve financial health, consider setting spending targets for each category and tracking against them.

--- End of Insights ---

---

# Part 3: Assignment Setup (20 minutes)

**🎉 Now for the exciting part - starting your actual assignment!**

## 📋 Assignment Template Overview

Your Smart Finance Assistant assignment has this structure:

```
smart-finance-assistant/
├── smart_finance_assistant.ipynb    # Main notebook
├── README.md                        # Project description
├── diary.md                         # Developer's diary
├── data/
│   └── sample_transactions.csv      # Your data files
└── requirements.txt                 # Python dependencies
```

## 🔨 Setting Up Your Assignment Repository

### Step 1: Fork the Template Repository

1. Go to: https://github.com/michael-borck/smart-finance-assistant
2. Click "Fork" to create your own copy
3. Clone your fork to your computer or open in Google Colab

### Step 2: Understand the Project Structure

Let's explore what you're building:

**Your Smart Finance Assistant will include:**
- 📊 **CSV Data Processing** (what we're learning today!)
- 💬 **Chat Interface** (AI personality for financial advice)
- 🔍 **RAG System** (retrieval from your transaction data)
- 🛠️ **Custom Tool** (like a savings calculator)
- 🌐 **Gradio UI** (simple web interface)

**Don't worry** - you'll build this incrementally over the next 5 weeks!

### Step 3: Locate Your Developer's Diary

Open the `diary.md` file in your repository. This is where you'll document your AI collaborations each week.

::: {.callout-important}
## Week 8 Diary Template

Your diary should include weekly "AI Evidence Packages" like this:

```markdown
## Week 8: Initial CSV Processing

### AI Collaboration #1
**Context**: Setting up basic CSV loading and analysis for transaction data
**Prompt**: "Help me load and analyze transaction CSV data for my finance assistant"
**Result**: Working pandas code with data cleaning and summary statistics
**Reflection**: AI provided good starting code, but I had to ask for better error handling

### AI Collaboration #2
**Context**: Creating spending summary by category
**Prompt**: "Calculate total spending by category and format for business presentation"
**Result**: Professional-looking output with proper formatting
**Reflection**: Learned to be specific about output formatting requirements
```
:::

---

# Part 4: Start Your Assignment! (40 minutes)

**This is it!** Time to make real progress on your Smart Finance Assistant.

## 🎯 Your Week 8 Assignment Goals

By the end of today, you should have:
1. ✅ Forked the assignment repository
2. ✅ Loaded transaction data successfully
3. ✅ Created basic spending summaries using AI assistance
4. ✅ Documented your AI interactions in the diary
5. ✅ Made your first meaningful commit

## 📊 Step 1: Set Up Your Data

**Open your assignment notebook** (`smart_finance_assistant.ipynb`) and start with this section:

### Data Loading and Exploration

::: {.callout-tip}
## Prompt AI for this section:

*"I'm building a Smart Finance Assistant for my programming assignment. I need to load a CSV file with transaction data (columns: Date, Amount, Category, Description). The Amount column has dollar signs that need cleaning. Please write professional Python code with detailed comments that:
1. Loads the CSV data
2. Cleans and validates the data
3. Shows basic information about the dataset
4. Handles any common data issues"*
:::

In [19]:
import pandas as pd
import os

# --- Configuration and File Path ---
# Define the directory and file path for the transaction data
data_dir = 'data'
file_name = 'sample_transactions.csv'
file_path = os.path.join(data_dir, file_name)

# Create the data directory if it doesn't exist
if not os.path.exists(data_dir):
    os.makedirs(data_dir)
    print(f"Created directory: {data_dir}/")

# Create a dummy CSV file if it doesn't exist to ensure the code can run
if not os.path.exists(file_path):
    dummy_data = {
        'Date': ['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04', '2023-01-05',
                 '2023-01-06', '2023-01-07', '2023-01-08', '2023-01-09', '2023-01-10'],
        'Amount': ['$50.00', '$25.50', '$120.00', '$30.75', '$75.00',
                   '$15.20', '$88.00', '$12.50', '$90.00', '$5.00'],
        'Category': ['Food', 'Transport', 'Shopping', 'Food', 'Utilities',
                     'Food', 'Shopping', 'Transport', 'Entertainment', 'Food'],
        'Description': ['Groceries', 'Bus fare', 'New clothes', 'Restaurant', 'Electricity bill',
                        'Coffee', 'Book', 'Train ticket', 'Movie', 'Snack']
    }
    dummy_df = pd.DataFrame(dummy_data)
    dummy_df.to_csv(file_path, index=False)
    print(f"Created dummy '{file_name}' at {file_path}")

# --- 1. Load the CSV data ---
try:
    df_transactions = pd.read_csv(file_path)
    print(f"\nSuccessfully loaded '{file_name}'")
except FileNotFoundError:
    print(f"Error: The file '{file_path}' was not found. Please ensure it exists.")
    # Exit or handle gracefully if file is crucial
    df_transactions = pd.DataFrame() # Create an empty DataFrame to avoid further errors

if not df_transactions.empty:
    # --- 2. Clean and validate the data ---
    print("\n--- Initial Data Info ---")
    df_transactions.info()

    # Convert 'Date' column to datetime objects
    # errors='coerce' will turn unparseable dates into NaT (Not a Time)
    df_transactions['Date'] = pd.to_datetime(df_transactions['Date'], errors='coerce')

    # Clean 'Amount' column: remove dollar signs and convert to numeric
    # errors='coerce' will turn unparseable amounts into NaN
    df_transactions['Amount'] = df_transactions['Amount'].astype(str).str.replace('$', '', regex=False)
    df_transactions['Amount'] = pd.to_numeric(df_transactions['Amount'], errors='coerce')

    # Handle potential data issues:
    # Drop rows where 'Date' or 'Amount' could not be parsed
    initial_rows = len(df_transactions)
    df_transactions.dropna(subset=['Date', 'Amount'], inplace=True)
    if len(df_transactions) < initial_rows:
        print(f"\nWarning: {initial_rows - len(df_transactions)} rows were dropped due to invalid 'Date' or 'Amount' values.")

    # Fill any remaining NaNs in 'Category' or 'Description' with 'Unknown'
    df_transactions['Category'].fillna('Unknown', inplace=True)
    df_transactions['Description'].fillna('No Description', inplace=True)

    # --- 3. Show basic information about the dataset ---
    print("\n--- Cleaned Data Info ---")
    df_transactions.info()

    print("\n--- First 5 rows of cleaned data ---")
    display(df_transactions.head())

    print("\n--- Basic Statistics for Numeric Columns ---")
    display(df_transactions.describe())

    print(f"\nTotal transactions after cleaning: {len(df_transactions)}")
    print(f"Date range: {df_transactions['Date'].min().strftime('%Y-%m-%d')} to {df_transactions['Date'].max().strftime('%Y-%m-%d')}")
    print(f"Unique Categories: {df_transactions['Category'].unique().tolist()}")
else:
    print("DataFrame is empty, cannot proceed with cleaning and validation.")

# Store the processed DataFrame for later use in the notebook
df = df_transactions.copy() # Assign to 'df' as used in subsequent cells

Created directory: data/
Created dummy 'sample_transactions.csv' at data/sample_transactions.csv

Successfully loaded 'sample_transactions.csv'

--- Initial Data Info ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Date         10 non-null     object
 1   Amount       10 non-null     object
 2   Category     10 non-null     object
 3   Description  10 non-null     object
dtypes: object(4)
memory usage: 452.0+ bytes

--- Cleaned Data Info ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Date         10 non-null     datetime64[ns]
 1   Amount       10 non-null     float64
 2   Category     10 non-null     object
 3   Description  10 non-null     object
dtypes: datetime64[ns](1), float64(1), object(2)
memory usage: 452.0+ bytes

--- First 5 rows of cleaned data ---

/tmp/ipykernel_2003/727886885.py:62: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_transactions['Category'].fillna('Unknown', inplace=True)
/tmp/ipykernel_2003/727886885.py:63: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_transactions['Description'].fillna('No Description', inplace=True)

        Date  Amount   Category       Description
0 2023-01-01   50.00       Food         Groceries
1 2023-01-02   25.50  Transport          Bus fare
2 2023-01-03  120.00   Shopping       New clothes
3 2023-01-04   30.75       Food        Restaurant
4 2023-01-05   75.00  Utilities  Electricity bill

--- Basic Statistics for Numeric Columns ---

                      Date     Amount
count                   10   10.00000
mean   2023-01-05 12:00:00   51.19500
min    2023-01-01 00:00:00    5.00000
25%    2023-01-03 06:00:00   17.77500
50%    2023-01-05 12:00:00   40.37500
75%    2023-01-07 18:00:00   84.75000
max    2023-01-10 00:00:00  120.00000
std                    NaN   39.67622

Total transactions after cleaning: 10
Date range: 2023-01-01 to 2023-01-10
Unique Categories: ['Food', 'Transport', 'Shopping', 'Utilities', 'Entertainment']

## 📈 Step 2: Create Core Analysis Functions

**Prompt AI** to help you create the foundation of your finance assistant:

::: {.callout-tip}
## Analysis Functions Prompt:

*"For my Smart Finance Assistant, I need functions to analyze spending data. Please create well-documented functions that:
1. Calculate total spending by category
2. Find the top 5 spending categories
3. Calculate average spending per transaction
4. Identify any unusual transactions (very high or negative amounts)
Each function should have clear business explanations and error handling."*
:::

In [20]:
import pandas as pd

# Ensure 'df' DataFrame is available from previous steps
# Assuming df is already cleaned and 'Amount' is numeric.
if 'df' not in globals() or df.empty:
    print("Error: DataFrame 'df' not found or is empty. Please run previous cells to load and clean data.")
    # Optionally, you could load a dummy df here for development if needed
    # For this exercise, we assume df is populated correctly.


def calculate_total_spending_by_category(df_transactions):
    """
    Calculates the total spending for each category.

    Args:
        df_transactions (pd.DataFrame): DataFrame with transaction data,
                                        must contain 'Category' and numeric 'Amount' columns.

    Returns:
        pd.Series: A Series with categories as index and total spending as values,
                   sorted in descending order.
    """
    if df_transactions.empty:
        print("Warning: No data to analyze for total spending by category.")
        return pd.Series()
    if 'Category' not in df_transactions.columns or 'Amount' not in df_transactions.columns:
        print("Error: DataFrame must contain 'Category' and 'Amount' columns.")
        return pd.Series()

    # Business Explanation: Understanding where the most money goes is crucial.
    # This helps identify primary expense areas.
    total_spending = df_transactions.groupby('Category')['Amount'].sum().sort_values(ascending=False)
    return total_spending


def find_top_n_spending_categories(df_transactions, n=5):
    """
    Identifies the top N categories by total spending.

    Args:
        df_transactions (pd.DataFrame): DataFrame with transaction data.
        n (int): The number of top categories to return.

    Returns:
        pd.Series: A Series of the top N categories and their total spending.
    """
    if df_transactions.empty:
        print("Warning: No data to analyze for top spending categories.")
        return pd.Series()

    total_spending = calculate_total_spending_by_category(df_transactions)
    if total_spending.empty:
        return pd.Series()

    # Business Explanation: Pinpointing the largest spending categories allows for focused
    # review and potential budget adjustments.
    top_categories = total_spending.head(n)
    return top_categories


def calculate_average_transaction_amount(df_transactions):
    """
    Calculates the average spending per transaction across all categories.

    Args:
        df_transactions (pd.DataFrame): DataFrame with transaction data.

    Returns:
        float: The average transaction amount.
    """
    if df_transactions.empty:
        print("Warning: No data to calculate average transaction amount.")
        return 0.0
    if 'Amount' not in df_transactions.columns:
        print("Error: DataFrame must contain an 'Amount' column.")
        return 0.0

    # Business Explanation: The average transaction amount can give insight into spending habits.
    # A high average might indicate fewer, larger purchases, while a low average suggests many small purchases.
    average_amount = df_transactions['Amount'].mean()
    return average_amount


def identify_unusual_transactions(df_transactions, high_threshold_multiplier=2.0, lower_bound=0):
    """
    Identifies transactions that are unusually high or negative.
    Unusually high is defined as 'Amount' greater than `high_threshold_multiplier` times the mean amount.

    Args:
        df_transactions (pd.DataFrame): DataFrame with transaction data.
        high_threshold_multiplier (float): Multiplier for the mean to set the 'unusually high' threshold.
        lower_bound (float): The lower limit for transaction amounts to be considered unusual (e.g., negative).

    Returns:
        pd.DataFrame: A DataFrame containing the unusual transactions.
    """
    if df_transactions.empty:
        print("Warning: No data to identify unusual transactions.")
        return pd.DataFrame()
    if 'Amount' not in df_transactions.columns:
        print("Error: DataFrame must contain an 'Amount' column.")
        return pd.DataFrame()

    # Business Explanation: Flagging unusual transactions helps to quickly spot potential errors,
    # fraudulent activity, or significant one-off expenses that might skew analysis.
    mean_amount = df_transactions['Amount'].mean()
    high_threshold = mean_amount * high_threshold_multiplier

    unusual_transactions = df_transactions[
        (df_transactions['Amount'] > high_threshold) |
        (df_transactions['Amount'] < lower_bound)
    ]
    return unusual_transactions


# --- Demonstration of the functions ---
print("\n--- Running Analysis Functions ---")

# 1. Total spending by category
total_by_category = calculate_total_spending_by_category(df)
print("\nTotal Spending by Category:")
print(total_by_category.to_string(float_format="${:,.2f}".format))

# 2. Top 5 spending categories
top_5_categories = find_top_n_spending_categories(df, n=5)
print("\nTop 5 Spending Categories:")
print(top_5_categories.to_string(float_format="${:,.2f}".format))

# 3. Average spending per transaction
avg_transaction = calculate_average_transaction_amount(df)
print(f"\nAverage Spending per Transaction: ${avg_transaction:,.2f}")

# 4. Unusual transactions
unusual_transactions_df = identify_unusual_transactions(df, high_threshold_multiplier=2.5, lower_bound=-0.01)
print("\nUnusual Transactions (e.g., very high or negative):")
if not unusual_transactions_df.empty:
    display(unusual_transactions_df)
else:
    print("No unusual transactions identified based on the criteria.")

--- Running Analysis Functions ---

Total Spending by Category:
Category
Shopping        $208.00
Food            $100.95
Entertainment    $90.00
Utilities        $75.00
Transport        $38.00

Top 5 Spending Categories:
Category
Shopping        $208.00
Food            $100.95
Entertainment    $90.00
Utilities        $75.00
Transport        $38.00

Average Spending per Transaction: $51.20

Unusual Transactions (e.g., very high or negative):
No unusual transactions identified based on the criteria.

## 💰 Step 3: Generate Business Insights

**Challenge AI** to help you create business-relevant insights:

::: {.callout-tip}
## Business Insights Prompt:

*"Using the transaction analysis functions, help me create a comprehensive spending report that would be useful for personal financial planning. Include recommendations for potential savings and spending pattern observations. Format it like a professional financial summary."*
:::

In [22]:
# AI-generated business insights for personal financial planning

print("\n--- Smart Finance Assistant: Personal Spending Report ---")
print("=" * 60)
print("Date: " + pd.Timestamp.now().strftime('%Y-%m-%d %H:%M:%S'))
print("Reporting Period: " + df['Date'].min().strftime('%Y-%m-%d') + " to " + df['Date'].max().strftime('%Y-%m-%d'))
print("=" * 60)

if not df.empty:
    # Use the analysis functions
    total_by_category = calculate_total_spending_by_category(df)
    top_categories = find_top_n_spending_categories(df, n=3) # Focusing on top 3 for summary
    avg_transaction = calculate_average_transaction_amount(df)
    unusual_transactions = identify_unusual_transactions(df, high_threshold_multiplier=3.0, lower_bound=0) # Slightly higher threshold for report
    grand_total_spending = df['Amount'].sum()

    print("\n### 📊 Executive Summary ###")
    print(f"During the period, your total spending across all categories was: ${grand_total_spending:,.2f}")
    print(f"The average amount per transaction was: ${avg_transaction:,.2f}")

    if not total_by_category.empty:
        print("\n### 💸 Spending Breakdown by Category ###")
        print(total_by_category.to_string(float_format="${:,.2f}".format))
        print("\n")

        print("### 💡 Key Spending Patterns & Recommendations ###")

        # Insight 1: Top Spending Categories
        if not top_categories.empty:
            print("\n**1. High-Impact Spending Areas:**")
            for category, amount in top_categories.items():
                print(f"   - '{category}' is a significant expense, totaling ${amount:,.2f}. This accounts for {amount/grand_total_spending:.1%} of your total spending.")
            print("   * **Recommendation:** Review transactions within these top categories. Are there opportunities to negotiate better deals, reduce discretionary spending, or seek more cost-effective alternatives?")

        # Insight 2: Frequent Small Purchases (if applicable)
        # For this, we'll look for categories with high transaction count but not necessarily highest total spend
        category_counts = df.groupby('Category')['Amount'].count().sort_values(ascending=False)
        # Filter out top spending categories to find other frequent ones
        frequent_small_purchases = category_counts[~category_counts.index.isin(top_categories.index)]
        if not frequent_small_purchases.empty and frequent_small_purchases.max() > 1:
            print("\n**2. Frequent Small Purchases:**")
            for category, count in frequent_small_purchases.head(2).items(): # Show top 2 other frequent categories
                 total_for_freq_cat = total_by_category.get(category, 0)
                 avg_for_freq_cat = total_for_freq_cat / count if count > 0 else 0
                 print(f"   - '{category}' has {count} transactions, averaging ${avg_for_freq_cat:,.2f} per transaction, totaling ${total_for_freq_cat:,.2f}.")
            print("   * **Recommendation:** Small, frequent expenditures can add up quickly. Consider setting a daily or weekly budget for these categories or explore alternatives like packing lunch instead of buying daily coffee/lunch.")

        # Insight 3: Unusual Transactions
        if not unusual_transactions.empty:
            print("\n**3. Unusual Transactions Identified:**")
            display(unusual_transactions[['Date', 'Category', 'Description', 'Amount']])
            print("   * **Recommendation:** Investigate these transactions to understand their nature. They might be one-off large expenses, errors, or opportunities for significant savings if they are recurring but not typical.")
        else:
            print("\n**3. No Highly Unusual Transactions:** No transactions significantly deviating from your average spending were detected in this period.")

    else:
        print("No category spending data to analyze.")

    print("\n--- End of Report ---")
    print("\n**Next Steps for Financial Planning:**")
    print(" - Set realistic budgets based on your spending patterns.")
    print(" - Track your spending regularly to stay within budget.")
    print(" - Look for recurring subscriptions or services that could be optimized.")
    print(" - Build an emergency fund to cover unexpected large expenses.")
else:
    print("No transaction data available to generate a spending report.")

--- Smart Finance Assistant: Personal Spending Report ---
============================================================
Date: 2026-04-27 19:34:36
Reporting Period: 2023-01-01 to 2023-01-10
============================================================

### 📊 Executive Summary ###
During the period, your total spending across all categories was: $511.95
The average amount per transaction was: $51.20

### 💸 Spending Breakdown by Category ###
Category
Shopping        $208.00
Food            $100.95
Entertainment    $90.00
Utilities        $75.00
Transport        $38.00


### 💡 Key Spending Patterns & Recommendations ###

**1. High-Impact Spending Areas:**
   - 'Shopping' is a significant expense, totaling $208.00. This accounts for 40.6% of your total spending.
   - 'Food' is a significant expense, totaling $100.95. This accounts for 19.7% of your total spending.
   - 'Entertainment' is a significant expense, totaling $90.00. This accounts for 17.6% of your total spending.
   * **Recommendation:** Review transactions within these top categories. Are there opportunities to negotiate better deals, reduce discretionary spending, or seek more cost-effective alternatives?

**2. Frequent Small Purchases:**
   - 'Transport' has 2 transactions, averaging $19.00 per transaction, totaling $38.00.
   - 'Utilities' has 1 transactions, averaging $75.00 per transaction, totaling $75.00.
   * **Recommendation:** Small, frequent expenditures can add up quickly. Consider setting a daily or weekly budget for these categories or explore alternatives like packing lunch instead of buying daily coffee/lunch.

**3. No Highly Unusual Transactions:** No transactions significantly deviating from your average spending were detected in this period.

--- End of Report ---

**Next Steps for Financial Planning:**
 - Set realistic budgets based on your spending patterns.
 - Track your spending regularly to stay within budget.
 - Look for recurring subscriptions or services that could be optimized.
 - Build an emergency fund to cover unexpected large expenses.

## 📝 Step 4: Document Your AI Interactions

**Important**: As you work, document each AI collaboration in your `diary.md` file.

**Template for each interaction:**

```markdown
### AI Collaboration #[number]
**Context**: [One sentence about what you were trying to achieve]
**Prompt**: "[Your exact prompt to AI]"
**Result**: [Brief description of what AI provided]
**Reflection**: [What worked well? What didn't? What you learned?]
```

---

# Part 5: Commit and Reflect (10 minutes)

## 💾 Making Your First Commit

You've made real progress! Time to commit your work:

```bash
# In your terminal/command line:
git add .
git commit -m "Week 8: Initial CSV processing and analysis implemented

- Set up data loading with error handling
- Created spending analysis functions  
- Generated business insights report
- Documented AI collaboration in diary

🤖 Generated with AI assistance - see diary.md for details"

git push origin main
```

## 🎯 Exit Ticket Success Criteria

**Congratulations! If you've completed the following, you've successfully completed your Week 8 exit ticket:**

- ☐ **Repository Setup**: Forked and cloned assignment template
- ☐ **Data Processing**: Successfully loaded and analyzed transaction CSV data
- ☐ **AI Collaboration**: Used AI to generate spending summary code
- ☐ **Documentation**: Recorded at least 3 AI interactions in Developer's Diary
- ☐ **Git Commit**: Made meaningful commit with progress description
- ☐ **Business Focus**: Created analysis relevant to personal finance

## 🏆 What You've Accomplished Today

**Technical Skills:**
- Transitioned to AI-assisted programming workflow
- Mastered basic pandas operations for business data
- Learned effective AI prompting techniques
- Practiced code critique and improvement skills

**Assignment Progress:**
- Your Smart Finance Assistant is already 10% complete!
- You have working CSV processing - the foundation of your project
- Your repository structure is set up professionally
- You've established a good AI collaboration workflow

**Professional Development:**
- Experienced modern programming practices
- Built confidence with real business data
- Learned to direct AI like a junior developer
- Created documentation habits that employers value

---

# 🚀 Next Steps and Week 9 Preview

**For Week 9**, you'll build on today's foundation by:
- Adding data visualization to your finance assistant
- Creating interactive filtering and analysis features
- Expanding your business insights with trend analysis
- Continuing to document your AI collaboration journey

**Assignment Momentum**: By completing Week 8's exit ticket today, you've given yourself a significant head start on your final project. Keep this momentum going!

**Remember**: You only need 6 out of 8 exit tickets to pass. By starting here, you're setting yourself up for success.

---

## 🤝 Need Help?

- **Stuck with AI prompts?** Review Module 3 for better prompt templates
- **Code not working?** Use Module 4's critique toolkit to debug with AI
- **Repository issues?** Ask your facilitator for Git help
- **Behind on progress?** Focus on getting one function working well rather than everything perfect

**Most importantly**: You're now a code director, not a code writer. Embrace the collaboration with AI and focus on understanding the business logic rather than memorizing syntax.

**Great work today! You've officially started your journey toward building a professional Smart Finance Assistant! 🎉**